"""Overall Entropy Score Aggregation Engine.

Aggregates category scores into the final Entropy Debt Score (0-100).

Strict Invariants:
1. Determinism: identical findings + codebase metrics yield identical scores.
2. Evidence-derived: score is calculated entirely from actual static analysis findings.
3. No fabricated data: only implemented, analyzed categories contribute to the score.
4. Scale normalization: repository size prevents false inflation.
5. Zero LLM involvement: purely static and mathematical.
6. Transparency: step-by-step audit trail included in every result.
"""

from __future__ import annotations

from app.models.domain.enums import DebtCategory, Severity
from app.models.domain.finding import Finding
from app.scoring.bands import clamp_score, classify_score_band
from app.scoring.category_scorer import CategoryScorer, category_scorer
from app.scoring.models import (
    CategoryScoreBreakdown,
    DebtScoreResult,
    NormalizationMetrics,
    RuleContribution,
    ScoringStatus,
)
from app.scoring.normalizer import ScoreNormalizer, normalizer
from app.scoring.weights import CATEGORY_WEIGHTS

# Default analyzed categories for Phase 6 (categories with active analyzers)
DEFAULT_ANALYZED_CATEGORIES: set[DebtCategory] = {
    DebtCategory.ERROR_HANDLING,
    DebtCategory.AUTHENTICATION_CONSISTENCY,
    DebtCategory.AUTHORIZATION_CONSISTENCY,
    DebtCategory.INPUT_VALIDATION,
    DebtCategory.LOGGING_AND_SECRETS,
}


class EntropyScorer:
    """Computes the authoritative Entropy Score from Phase 3 findings."""

    def __init__(
        self,
        category_scorer_instance: CategoryScorer | None = None,
        normalizer_instance: ScoreNormalizer | None = None,
    ) -> None:
        self.category_scorer = category_scorer_instance or category_scorer
        self.normalizer = normalizer_instance or normalizer

    def calculate_score(
        self,
        findings: list[Finding],
        total_loc: int = 0,
        analyzed_files: int = 0,
        skipped_files: int = 0,
        analyzed_categories: set[DebtCategory] | None = None,
    ) -> DebtScoreResult:
        """Calculate the comprehensive Entropy Score.

        Parameters
        ----------
        findings : list[Finding]
            Deterministic findings generated by Phase 3 static analyzers.
        total_loc : int
            Total source lines of code analyzed.
        analyzed_files : int
            Number of source files inspected.
        skipped_files : int
            Number of files excluded safely during ingestion.
        analyzed_categories : set[DebtCategory] | None
            Set of categories that currently have active analyzers implemented.
            Defaults to {DebtCategory.ERROR_HANDLING} for Phase 4.
        """
        active_cats = analyzed_categories if analyzed_categories is not None else DEFAULT_ANALYZED_CATEGORIES

        # Group findings by category
        grouped_findings: dict[DebtCategory, list[Finding]] = {cat: [] for cat in DebtCategory}
        for f in findings:
            if f.category in grouped_findings:
                grouped_findings[f.category].append(f)

        category_breakdowns: dict[DebtCategory, CategoryScoreBreakdown] = {}
        audit_trail: list[str] = [
            f"Initialized Entropy scoring for {len(findings)} finding(s) across "
            f"{analyzed_files} file(s) ({total_loc} LOC)."
        ]

        # Calculate category scores
        for category in DebtCategory:
            is_analyzed = category in active_cats
            cat_findings = grouped_findings[category]
            breakdown = self.category_scorer.score_category(
                category=category,
                findings=cat_findings,
                is_analyzed=is_analyzed,
                total_loc=total_loc,
                analyzed_files=analyzed_files,
            )
            category_breakdowns[category] = breakdown

        # Calculate relative weights across analyzed categories
        total_active_base_weight = sum(CATEGORY_WEIGHTS.get(c, 0.0) for c in active_cats)
        audit_trail.append(
            f"Active analyzed categories ({len(active_cats)}): "
            f"{', '.join(c.value for c in active_cats)} "
            f"(combined base weight: {total_active_base_weight:.2f})."
        )

        total_weighted_score = 0.0

        if total_active_base_weight > 0:
            for cat in active_cats:
                cat_breakdown = category_breakdowns[cat]
                base_w = CATEGORY_WEIGHTS.get(cat, 0.0)
                relative_weight = base_w / total_active_base_weight
                cat_score = cat_breakdown.score if cat_breakdown.score is not None else 0.0
                weighted_contribution = cat_score * relative_weight

                # Update weighted score in breakdown
                cat_breakdown.weighted_score = round(weighted_contribution, 2)
                total_weighted_score += weighted_contribution

                audit_trail.append(
                    f"[{cat.value}] Score: {cat_score:.1f}/100 × Relative Weight {relative_weight:.2f} "
                    f"= {weighted_contribution:.2f} pts (Findings: {cat_breakdown.finding_count})"
                )
        else:
            audit_trail.append("Warning: No active analyzed categories configured. Total score set to 0.")

        final_score = clamp_score(total_weighted_score)
        tier = classify_score_band(final_score)

        # Aggregate severity breakdown
        severity_breakdown = {s: 0 for s in Severity}
        for f in findings:
            if f.category in active_cats:
                severity_breakdown[f.severity] += 1

        # Aggregate top rules across all analyzed categories
        all_top_rules: list[RuleContribution] = []
        for cat in active_cats:
            all_top_rules.extend(category_breakdowns[cat].top_rules)
        all_top_rules.sort(key=lambda r: (r.weighted_points, r.finding_count), reverse=True)

        scale_factor = self.normalizer.calculate_scale_factor(total_loc)
        normalization_metrics = NormalizationMetrics(
            total_loc=total_loc,
            analyzed_files=analyzed_files,
            kloc=round(max(total_loc, 0) / 1000.0, 3),
            scale_factor=round(scale_factor, 3),
            formula=(
                f"Scale_Factor = max(1.0, sqrt({total_loc} / 500)) = {scale_factor:.2f}; "
                f"Active_Weights_Sum = {total_active_base_weight:.2f}"
            ),
        )

        formula_summary = (
            "Entropy_Score = Round( Σ (Category_Score_i × (Weight_i / Σ Active_Weights)) ), where "
            "Category_Score = 100 × (1 - exp(-Normalized_Penalty / 25.0)) and "
            "Normalized_Penalty = Raw_Penalty / max(1.0, sqrt(LOC / 500))"
        )

        audit_trail.append(
            f"Final Aggregated Entropy Score: {final_score}/100 ({tier.label}). "
            f"Status: AVAILABLE. Fully deterministic and evidence-backed."
        )

        return DebtScoreResult(
            total_score=final_score,
            tier=tier,
            status=ScoringStatus.AVAILABLE,
            analyzed_categories=sorted(list(active_cats)),
            category_scores=category_breakdowns,
            total_findings=len(findings),
            total_loc=total_loc,
            analyzed_files=analyzed_files,
            skipped_files=skipped_files,
            severity_breakdown=severity_breakdown,
            top_contributing_rules=all_top_rules[:10],
            normalization=normalization_metrics,
            formula_summary=formula_summary,
            audit_trail=audit_trail,
            is_explainable=True,
        )


entropy_scorer = EntropyScorer()
